version: '3'

services:
  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - db
      - rabbitmq
networks:
  default:
    external:
      name: my-network